# Generated by Django 4.2.7 on 2023-12-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0003_etas_time_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='etas',
            name='method_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
